# Generated by Django 2.1.1 on 2018-10-31 07:23

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo mới')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục blog',
                'verbose_name_plural': 'Danh mục blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo mới')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('content', models.TextField(verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo mới')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Tác giả')),
                ('main_img', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh blog')),
                ('paragraph_1', models.TextField(blank=True, verbose_name='Đoạn 1')),
                ('img_1', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 1')),
                ('img_description_1', models.CharField(max_length=300, verbose_name='Caption ảnh 1')),
                ('paragraph_2', models.TextField(blank=True, verbose_name='Đoạn 2')),
                ('img_2', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 2')),
                ('img_description_2', models.CharField(max_length=300, verbose_name='Caption ảnh 2')),
                ('paragraph_3', models.TextField(blank=True, verbose_name='Đoạn 3')),
                ('img_3', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 3')),
                ('img_description_3', models.CharField(max_length=300, verbose_name='Caption ảnh 3')),
                ('paragraph_4', models.TextField(blank=True, verbose_name='Đoạn 4')),
                ('img_4', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 4')),
                ('img_description_4', models.CharField(max_length=300, verbose_name='Caption ảnh 4')),
                ('paragraph_5', models.TextField(blank=True, verbose_name='Đoạn 5')),
                ('img_5', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 5')),
                ('img_description_5', models.CharField(max_length=300, verbose_name='Caption ảnh 5')),
                ('paragraph_6', models.TextField(blank=True, verbose_name='Đoạn 6')),
                ('img_6', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 6')),
                ('img_description_6', models.CharField(max_length=300, verbose_name='Caption ảnh 6')),
                ('paragraph_7', models.TextField(blank=True, verbose_name='Đoạn 7')),
                ('img_7', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 7')),
                ('img_description_7', models.CharField(max_length=300, verbose_name='Caption ảnh 7')),
                ('paragraph_8', models.TextField(blank=True, verbose_name='Đoạn 8')),
                ('img_8', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh 8')),
                ('img_description_8', models.CharField(max_length=300, verbose_name='Caption ảnh 8')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory')),
            ],
            options={
                'verbose_name': 'Bài blog',
                'verbose_name_plural': 'Bài blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost', verbose_name='Bài blog'),
        ),
        migrations.AlterIndexTogether(
            name='blogpost',
            index_together={('id', 'slug')},
        ),
    ]
