# Generated by Django 2.1.1 on 2018-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_1',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 1'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_3',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 3'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_4',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 4'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_5',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 5'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_6',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 6'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_7',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 7'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='img_description_8',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption ảnh 8'),
        ),
    ]
