# Generated by Django 2.1.1 on 2018-11-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181103_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='allow',
            field=models.BooleanField(blank=True, default=True, verbose_name='Cho phép'),
        ),
    ]
