# Generated by Django 2.1.1 on 2018-11-12 10:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_6',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_7',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_8',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_6',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_7',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='img_description_8',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_6',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_7',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='paragraph_8',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hashtag',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
