# Generated by Django 2.1.1 on 2018-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Giới thiệu'),
        ),
    ]
