# Generated by Django 2.1.1 on 2018-11-10 15:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_auto_20181110_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_1', models.CharField(max_length=500)),
                ('color_1', colorfield.fields.ColorField(default='#f2f2f2', max_length=18)),
                ('text_2', models.CharField(max_length=500)),
                ('color_2', colorfield.fields.ColorField(default='#f2f2f2', max_length=18)),
                ('text_3', models.CharField(max_length=500)),
                ('color_3', colorfield.fields.ColorField(default='#f2f2f2', max_length=18)),
                ('text_4', models.CharField(max_length=500)),
                ('color_4', colorfield.fields.ColorField(default='#f2f2f2', max_length=18)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
