# Generated by Django 2.1.1 on 2018-11-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
    ]
