# Generated by Django 2.1.1 on 2018-11-10 15:49

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0005_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='color_1',
            field=colorfield.fields.ColorField(blank=True, default='#f2f2f2', max_length=18),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color_2',
            field=colorfield.fields.ColorField(blank=True, default='#f2f2f2', max_length=18),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color_3',
            field=colorfield.fields.ColorField(blank=True, default='#f2f2f2', max_length=18),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color_4',
            field=colorfield.fields.ColorField(blank=True, default='#f2f2f2', max_length=18),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_4',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
