# Generated by Django 2.1.1 on 2018-11-12 14:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0007_auto_20181110_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên'),
        ),
    ]
