# Generated by Django 2.1 on 2018-08-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_introduction_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
