# Generated by Django 2.1 on 2018-09-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Description',
            new_name='Introduction',
        ),
    ]
