# Generated by Django 2.1 on 2018-09-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180907_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
