# Generated by Django 2.1.1 on 2018-09-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180918_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_phong_thuy',
            field=models.BooleanField(blank=True, default=False, verbose_name='Top cây phong thủy'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_suc_khoe',
            field=models.BooleanField(blank=True, default=False, verbose_name='Top cây tốt cho sức khỏe'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_trang_tri',
            field=models.BooleanField(blank=True, default=False, verbose_name='Top cây trang trí'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
