# Generated by Django 2.1.1 on 2018-10-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='stt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
