# Generated by Django 2.1.1 on 2018-10-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20181001_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cd_chua_benh',
            field=models.BooleanField(default=False, verbose_name='Công dụng: Chữa bệnh'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_gia_vi',
            field=models.BooleanField(default=False, verbose_name='Công dụng: Gia vị'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_loc_khong_khi',
            field=models.BooleanField(default=False, verbose_name='Công dụng: Lọc không khí'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_nha_o2',
            field=models.BooleanField(default=False, verbose_name='Công dụng: Nhả O2 ban đêm'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_phong_thuy',
            field=models.BooleanField(default=False, verbose_name='Công dụng: Phong thủy'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_trang_tri',
            field=models.BooleanField(default=False, verbose_name='Công dụng: Trang trí'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.Category', verbose_name='Danh mục'),
        ),
    ]
