# Generated by Django 2.1.1 on 2018-10-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20181001_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='usage',
        ),
    ]
