# Generated by Django 2.1.1 on 2018-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20181110_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['stt', '-updated_at'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AddField(
            model_name='product',
            name='stt',
            field=models.PositiveIntegerField(default=1000, verbose_name='STT'),
        ),
    ]
