# Generated by Django 2.1 on 2018-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='...', help_text='Họ và tên', max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='Địa chỉ', max_length=150, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text='Số điện thoại', max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
